version: "3.7"
services:
  redis:
    image: redis
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379

  app:
    build:
      context: .
    env_file:
      - .env-docker
    container_name: fastapi_app
    command: ["/docker/app.sh"]
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - redis

